version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - echo "Entered to the pre build phase"
  build:
    commands:
    - echo "Entered to the build phase"
    - php --version
  post_build:
    commands:
    - echo "Entered to the post build phase"
artifacts:
  files:
    - '**/*'